### ISSUE TITLE
不知道能不能补充一下，运行步骤，不是很了解py，但是想体验一下

### ISSUE THREAD

**Issue by xiaohuoni** [zzzzzzhang/LOL-ydzy#1]

**Comment by zzzzzzhang** [comment]
惊现一只大佬，已经更新md~安装pandas库，matpoltlib库之后可以直接双击运行

**Comment by xiaohuoni** [comment]
哈哈哈，最近沉迷游戏，无法自拔（手动捂脸）

**Comment by xiaohuoni** [comment]
发生异常: ModuleNotFoundError
No module named 'pandas'
  File "/Users/xiaohuoni/Downloads/LOL-ydzy-master/YD-GA_cmd.py", line 6, in <module>
    import pandas as pd

**Comment by zzzzzzhang** [comment]
需要安装pandas库和matplotlib库~几行命令百度一下

**Comment by xiaohuoni** [comment]
ok
