### ISSUE TITLE
虚空羁绊发生了变化，希望楼主更新一下

### ISSUE THREAD

**Issue by xunwumizhi** [zzzzzzhang/LOL-ydzy#2]
如题，感谢，楼主棒棒哒

**Comment by xunwumizhi** [comment]
建议把羁绊和铲子转职信息也放到配置文件里面，爬虫运行时可以一起更新

**Comment by zzzzzzhang** [comment]
> 建议把羁绊和铲子转职信息也放到配置文件里面，爬虫运行时可以一起更新
虚空羁绊更新啦，最近实验室项目烦...有时间再改改配置文件那个哈哈

**Comment by 583704044** [comment]
楼组你好，因为改版了，你那个爬数据代码我这运行出来是两个空文件，是代码问题吗

**Comment by zzzzzzhang** [comment]
> 楼组你好，因为改版了，你那个爬数据代码我这运行出来是两个空文件，是代码问题吗

sorry :(  改版之后再也没玩过，可能目标网站已经改动了吧
希望有对这个程序有兴趣的旁友继续更新
（maybe过段时间闲下来我自己也会更新）

**Comment by 583704044** [comment]
楼主我不会爬数据，楼主能不能把新版本数据爬出来上传一下，谢谢楼主
